# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rwme <- function(sigma, xo, N) {
    .Call('_SC19074_rwme', PACKAGE = 'SC19074', sigma, xo, N)
}

